services:
  - type: web
    name: final-project-backend
    env: node
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: CORS_ORIGIN
        value: "https://final-project-frontend-3xot.onrender.com"  # put your actual frontend URL

  - type: static
    name: final-project-frontend
    buildCommand: cd frontend && npm install --include=dev && npx ng build --configuration production
    staticPublishPath: frontend/dist/ipt-2026-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
